### ISSUE TITLE
No `#pragma once` in Propware::Ping

### ISSUE THREAD

**Issue by BloodWorkXGaming** [parallaxinc/PropWare#147]
Causes ` error: redefinition of 'class PropWare::Ping'` when using in multiple files

**Comment by DavidZemon** [comment]
Thanks for finding this!

**Comment by BloodWorkXGaming** [comment]
Thanks for fixing it so quickly!

David Zemon <notifications@github.com> schrieb am Mi., 9. Jan. 2019, 16:04:
