### ISSUE TITLE
Installer replacing Cmake on linux

### ISSUE THREAD

**Issue by l0wl3vel** [parallaxinc/PropWare#162]
Since Propware seems to require some sort of patched CMake, is it possible to just use the pwcmake program in /usr/pwcmake/ and not replace the distros CMake with the outdated and patched one that comes with Propware? It seems kind of unnecessary to do this and is pretty hacky.

**Comment by DavidZemon** [comment]
What version of PropWare are you using? This _should_ have been fixed with #150, which was merged into the `develop` branch on Jan 20, 2019 (build 193 of v3.0.0).

**Comment by l0wl3vel** [comment]
Version 2.1.0 from the github releases section.

**Comment by DavidZemon** [comment]
Ah, yea I haven't made an "official" release of 3.0.0 yet, which is why you won't see it there, but it's definitely the version I'd recommend using. PropWare's website links to that version for downloading as well: https://david.zemon.name/PropWare/#/download
