### ISSUE TITLE
SPI improvements

### ISSUE THREAD

**Issue by konimaru** [parallaxinc/PropWare#92]
> Clock will run at 4 MHz with a sustained 3.33 Mbps average bitrate over multiple bytes.

[Interested in a 6.66MHz clock and 5Mbps average bit rate?
](https://github.com/konimaru/waitvid.2048/blob/master/coreView/src/coreView.1K.SPI.spin#L108)

**Comment by DavidZemon** [comment]
Of course! Thanks for opening a ticket for this! It's something I've wanted for a while but never had the sample code in front of me to implement :)

**Comment by DavidZemon** [comment]
I'm going to close this issue in favor of the method provided in #97. It looks to be very similar, but uses an unrolled loop.
